### PR TITLE
Few changes needs for my implement

### PR DESCRIPTION
**Pull request by spagr**
Sklik API using 20170905T17:06:10+0200 DateTime format, so there is little extension for that.

### CODE REVIEW

**Comment by milo** [comment]
Thanks for the PR. I'll merge it. One question. According to http://xmlrpc.scripting.com/spec.html, an empty `<array>` element is not allowed, it have to contain `<data>` always. You hit this problem with Sklik or in your own RPC server?

**Comment by spagr** [comment]
Thank for this library.
I'm not any xml-rpc spec guru and You're right, there in no clerly empty `<array>` element, but 
The following error occurred while parsing Sklik API response for client.get call :
Recoverable Error
Argument 1 passed to Milo\XmlRpc\Coder::decodeValueNode() must be an instance of DOMElement, instance of DOMText given, called in **************\vendor\milo\xml-rpc\src\XmlRpc\Coder.php on line 310 and defined

Response was :
```xml
<?xml version="1.0"?>
<methodResponse>
<params>
<param>
<value>
<struct>
<member>
<name>status</name>
<value><i4>200</i4></value>
</member>
<member>
<name>session</name>
<value><string>********MDRkZ2I3Y2MxBAIOEQFkZQ==</string></value>
</member>
<member>
<name>sessionStarted</name>
<value><dateTime.iso8601>20170906T08:21:08+0200</dateTime.iso8601></value>
</member>
<member>
<name>foreignAccounts</name>
<value>
<array>
<data>
</data>
</array>
</value>
</member>
<member>
<name>statusMessage</name>
<value><string>OK</string></value>
</member>
<member>
<name>user</name>
<value>
<struct>
<member>
<name>username</name>
<value><string>*****@*******.com</string></value>
</member>
<member>
<name>walletCredit</name>
<value><i4>187632</i4></value>
</member>
<member>
<name>accountLimit</name>
<value><nil/></value>
</member>
<member>
<name>dayBudgetSum</name>
<value><nil/></value>
</member>
<member>
<name>agencyStatus</name>
<value><string>normal</string></value>
</member>
<member>
<name>walletVerified</name>
<value><boolean>1</boolean></value>
</member>
<member>
<name>walletCreditWithVat</name>
<value><i4>227035</i4></value>
</member>
<member>
<name>userId</name>
<value><i4>1111111</i4></value>
</member>
</struct>
</value>
</member>
</struct>
</value>
</param>
</params>
</methodResponse>
```

**Comment by milo** [comment]
@spagr OK.

**Comment by milo** [comment]
Merged as dc4cabbb1947be34170e971a967f09ddf149945a and ae18f8c8ca84f764cf122aeddd36f4b2eb8e39f4

**Comment by spagr** [comment]
Hello,
You partly use my commit, 
omited condition 
`if ($value->nodeType == XML_ELEMENT_NODE) {`
in 
new version 2.1 can't handle empty `<data>` element under `<array>` node, try to convert this response :

```xml
<?xml version="1.0"?>
<methodResponse>
<params>
<param>
<value>
<struct>
<member>
<name>status</name>
<value><i4>200</i4></value>
</member>
<member>
<name>session</name>
<value><string>********MDRkZ2I3Y2MxBAIOEQFkZQ==</string></value>
</member>
<member>
<name>sessionStarted</name>
<value><dateTime.iso8601>20170906T08:21:08+0200</dateTime.iso8601></value>
</member>
<member>
<name>foreignAccounts</name>
<value>
<array>
<data>
</data>
</array>
</value>
</member>
<member>
<name>statusMessage</name>
<value><string>OK</string></value>
</member>
<member>
<name>user</name>
<value>
<struct>
<member>
<name>username</name>
<value><string>*****@*******.com</string></value>
</member>
<member>
<name>walletCredit</name>
<value><i4>187632</i4></value>
</member>
<member>
<name>accountLimit</name>
<value><nil/></value>
</member>
<member>
<name>dayBudgetSum</name>
<value><nil/></value>
</member>
<member>
<name>agencyStatus</name>
<value><string>normal</string></value>
</member>
<member>
<name>walletVerified</name>
<value><boolean>1</boolean></value>
</member>
<member>
<name>walletCreditWithVat</name>
<value><i4>227035</i4></value>
</member>
<member>
<name>userId</name>
<value><i4>1111111</i4></value>
</member>
</struct>
</value>
</member>
</struct>
</value>
</param>
</params>
</methodResponse>
```

**Comment by milo** [comment]
Yes. Sorry, I tested it without whitespaces. I'll fix it.

**Comment by milo** [comment]
Fixed in v2.2.0

**Comment by spagr** [comment]
:+1: 
Thank You

**Pull request closed without merging**
